### ISSUE TITLE
Random crash during resize.

### ISSUE THREAD

**Issue by Andrew123098** [carterjandrew/CSCI-2275-Final-Project#11]
Similar to crash during Divise Maze. No idea why it is happening, but I can replicate it by just resizing a few times. I see you know about this bug in the readme.

**Comment by carterjandrew** [comment]
Hmm... cant seem to replicate this on my end. I tried repeating it 10 times and nothing happened.

**Comment by Andrew123098** [comment]
Try printing between resizing or redivising the maze between

**Comment by carterjandrew** [comment]
Pointer was not being set when downscaling maze caused crashes.
